// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations (migrate dev/deploy, db seed via CLI) must use a DIRECT connection.
    // Supabase's transaction pooler (port 6543) cannot run DDL/advisory locks, so point
    // the CLI at DIRECT_URL (Supabase "Session" pooler / direct connection). The app
    // runtime instead connects through DATABASE_URL (the transaction pooler) via the
    // pg driver adapter in src/lib/db.ts. Falls back to DATABASE_URL for local dev.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
